# Generated by Django 6.0.5 on 2026-05-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_erpintegrationlog_erpintegrationsetting_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='half_day_option',
            field=models.CharField(choices=[('FULL', 'Full Day'), ('MORNING', 'Morning (Half Day)'), ('AFTERNOON', 'Afternoon (Half Day)')], default='FULL', max_length=10),
        ),
    ]
